/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionTokenRouteImport } from './routes/session.$token'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminHitlRouteImport } from './routes/admin.hitl'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionTokenRoute = SessionTokenRouteImport.update({
  id: '/session/$token',
  path: '/session/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHitlRoute = AdminHitlRouteImport.update({
  id: '/admin/hitl',
  path: '/admin/hitl',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/hitl': typeof AdminHitlRoute
  '/admin/login': typeof AdminLoginRoute
  '/session/$token': typeof SessionTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/hitl': typeof AdminHitlRoute
  '/admin/login': typeof AdminLoginRoute
  '/session/$token': typeof SessionTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/hitl': typeof AdminHitlRoute
  '/admin/login': typeof AdminLoginRoute
  '/session/$token': typeof SessionTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/customers'
    | '/admin/hitl'
    | '/admin/login'
    | '/session/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/customers'
    | '/admin/hitl'
    | '/admin/login'
    | '/session/$token'
  id:
    | '__root__'
    | '/'
    | '/admin/customers'
    | '/admin/hitl'
    | '/admin/login'
    | '/session/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminHitlRoute: typeof AdminHitlRoute
  AdminLoginRoute: typeof AdminLoginRoute
  SessionTokenRoute: typeof SessionTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$token': {
      id: '/session/$token'
      path: '/session/$token'
      fullPath: '/session/$token'
      preLoaderRoute: typeof SessionTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/hitl': {
      id: '/admin/hitl'
      path: '/admin/hitl'
      fullPath: '/admin/hitl'
      preLoaderRoute: typeof AdminHitlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminHitlRoute: AdminHitlRoute,
  AdminLoginRoute: AdminLoginRoute,
  SessionTokenRoute: SessionTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
